import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { getCorsHeaders } from "../_shared/cors.ts";
import { verifyAdmin } from "../_shared/auth.ts";

serve(async (req) => {
  const corsHeaders = getCorsHeaders(req);

  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    console.info('Starting Automotive sector content seed...');

    const { adminClient: supabase, error: authError } = await verifyAdmin(req, corsHeaders);
    if (authError) return authError;

    // Get the existing Automotive page
    const { data: existingPage, error: pageError } = await supabase
      .from('pages')
      .select('id')
      .eq('slug', 'sectors/automotive')
      .single();

    if (pageError || !existingPage) {
      console.error('Automotive page not found:', pageError);
      return new Response(
        JSON.stringify({ error: 'Automotive page not found' }),
        { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const pageId = existingPage.id;
    console.info(`Found existing Automotive page: ${pageId}`);

    // Delete existing sections and sources
    await supabase.from('page_sections').delete().eq('page_id', pageId);
    await supabase.from('page_sources').delete().eq('page_id', pageId);
    console.info('Deleted existing sections and sources');

    // Define all sections
    const sections = [
      // Introduction
      { section_id: 'intro-1', section_type: 'heading', title: 'Automotive', sort_order: 1, content: { level: 1 } },
      { section_id: 'intro-2', section_type: 'paragraph', title: null, sort_order: 2, content: { text: 'Automobiles, including cars, vehicles, trucks, and other wheeled passenger or commercial vehicles, play a significant role in our societal framework. The transportation sector accounts for 23% of worldwide energy-related carbon dioxide (CO2) emissions.' } },
      { section_id: 'intro-3', section_type: 'paragraph', title: null, sort_order: 3, content: { text: 'The primary obstacle to decarbonisation is in the identification and administration of carmakers\' supply chains. The automobile industry relies extensively on suppliers, and a single end-product is the culmination of an assembly line including thousands of components, the majority of which are manufactured off-site from the car manufacturer\'s premises. The automobile sector is a prosperous market that is projected to experience a growth rate of 36.2% by the year 2027. The key stakeholders in the industry are responding to the requirements for reducing carbon emissions by embracing and investing in emerging technologies such as electric vehicles (EVs), autonomous driving, and fuel cell vehicles (FCVs).' } },
      { section_id: 'intro-4', section_type: 'paragraph', title: null, sort_order: 4, content: { text: 'Identifiable factors that prompt change have been recognized to steer manufacturers towards a risk management approach that maximizes current prospects. In order for the automotive industry to attain Net-Zero emissions, it is necessary to implement innovative technology and implement effective policies that promote the use of electric vehicles on existing road networks. In order for the automobile industry to achieve the Net Zero scenario, it is essential to implement a variety of decarbonization measures. This comprehensive strategy must include technical innovation, supply chain optimization, and consumer behavior modification.' } },

      // Best Practices Section
      { section_id: 'bp-1', section_type: 'heading', title: 'Best practices', sort_order: 10, content: { level: 2 } },
      { section_id: 'bp-2', section_type: 'heading', title: 'Best practices in the automotive production processes', sort_order: 11, content: { level: 2 } },
      { section_id: 'bp-3', section_type: 'paragraph', title: null, sort_order: 12, content: { text: 'The first step entails the implementation of ambitious and feasible measures to reduce emissions through strategic planning. Nevertheless, automotive manufacturers (OEMs) are unable to realise their strategic objectives in the absence of appropriate foundations. In order to identify the most effective practices, it is necessary to categorise the production phases of the automotive manufacturer. In order to further establish a connection between the climate impact and the production phases, the financial institution must evaluate whether the car manufacturer has conducted a Life-Cycle Assessment of its production processes. LCAs enable the automotive manufacturer to facilitate decision-making during the early stages of the design process, thereby enhancing cost-effectiveness and enhancing the capacity to identify the areas in which the manufacturer needs to invest or modify in order to more effectively plan the achievement of its climate objectives. There are 3 phases in the Life Cycle Inventory (LCI) of an automotive manufacturer, those are production stage, use stage, and end-of-life. To those, there is a need to add the design stage, where the automotive producers choose how to build and manufacture their products.' } },
      { section_id: 'bp-4', section_type: 'paragraph', title: null, sort_order: 13, content: { text: 'Based on LCA and LCI studies, the following stages have been identified for the production process in the automotive sector. Moreover, stages of sustainability incorporation within the value chain have been identified.' } },
      { section_id: 'bp-5', section_type: 'list', title: 'Production Process Stages', sort_order: 14, content: { items: ['Development and design stage', 'Production stage - Covers the entire construction process, from raw material extraction till the manufacturing of car components.', 'Use stage - Includes the sub-stages of car operation and the emissions during operations.', 'End of life stage - Can be divided into 4 distinct steps: depollution, dismantling, shredding, and post-shredding technologies. This stage has been modeled following the principles of Directive EC/2000/53 and ISO standard 22628:2002.'] } },

      // Design and Development Stage
      { section_id: 'design-1', section_type: 'heading', title: 'Design and development stage', sort_order: 20, content: { level: 2 } },
      { section_id: 'design-2', section_type: 'paragraph', title: null, sort_order: 21, content: { text: 'Automakers can improve fuel efficiency through the physical design of their vehicles to reduce carbon emissions. Better aerodynamics can reduce drag and consequently engine size and battery as well. Lightweight design can also be used to improve the fuel economy of automobiles. Design for recyclability is another key facet that must be embedded into the design process to ensure manufacturers meet their Extended Producer Responsibilities (EPR).' } },
      { section_id: 'design-3', section_type: 'paragraph', title: null, sort_order: 22, content: { text: 'Technological advancement in developing more efficient powertrains, advanced transmissions, and regenerative braking systems can also be used to increase fuel efficiency. In conjunction with ever-improving battery technology, advancements in these areas will lead to reduced carbon emissions.' } },
      { section_id: 'design-4', section_type: 'paragraph', title: null, sort_order: 23, content: { text: 'The recyclability of a vehicle is also down to the ease of disassembly. With a range of materials used throughout, products cannot be recycled as a whole, and therefore component disassembly must be considered during design. This can involve quick release fasteners and other manufacturing methods for end-of-life disposal.' } },

      // Production Stage
      { section_id: 'prod-1', section_type: 'heading', title: 'Production stage', sort_order: 30, content: { level: 2 } },
      { section_id: 'prod-2', section_type: 'heading', title: 'Procurement', sort_order: 31, content: { level: 3 } },
      { section_id: 'prod-3', section_type: 'paragraph', title: null, sort_order: 32, content: { text: 'The significance of securing access to rare earth elements and vital components remains a pivotal concern for automakers engaged in the development and production of electric vehicles (EVs). The European Union (EU) acknowledges the imperative of maintaining its industrial competitiveness to prevent the risk of lagging behind nations like China and the United States.' } },
      { section_id: 'prod-4', section_type: 'paragraph', title: null, sort_order: 33, content: { text: 'Globalization has heightened complexity within the automotive supply chain, marked by substantial reliance on international trade and other countries to procure the necessary components for vehicle manufacturing. With potential for geopolitical instability, trade disputes, and disease outbreaks, there is a high likelihood that the EV transition could be disrupted and public perception of green technology damaged.' } },
      { section_id: 'prod-5', section_type: 'callout', title: 'Chip Shortages Impact', sort_order: 34, content: { type: 'warning', text: 'Recent chip shortages have caused difficulties for many manufacturers, resulting in overall output decreasing by over 23 per cent in the year to date. This has caused a revitalisation of the second-hand automotive market, which whilst viable for fossil-fueled vehicles, is not possible for EVs, which have smaller secondary market.' } },
      { section_id: 'prod-6', section_type: 'paragraph', title: null, sort_order: 35, content: { text: 'Electric vehicle (EV) batteries are significantly reliant on resources such as lithium (60kg), cobalt, copper, nickel, and graphite. These materials are frequently located in regions characterized by geopolitical sensitivity or instability, which heightens apprehensions regarding both the stability of the supply chain and the ethical aspects of sourcing. Whilst initiatives such as the EU Conflicts Minerals Regulations aim to combat this, there are opportunities to strengthen the supply chain elsewhere.' } },
      { section_id: 'prod-7', section_type: 'heading', title: 'Manufacturing', sort_order: 36, content: { level: 3 } },
      { section_id: 'prod-8', section_type: 'paragraph', title: null, sort_order: 37, content: { text: 'In the manufacturing process, thousands of incremental refinements can be used to achieve significant efficiency gains over time. Energy efficiency improvements are vital in reaching net zero. Energy-intensive activities from energy consumption of material transformation, such as stamping, casting, and painting, are the most energy intensive stages of vehicle manufacturing. An opportunity to utilise and further develop heat pump technology means manufacturers can capture their waste heat from refrigeration and utilise it for other production purposes. Digital twins and AI tools enable auto manufacturers to trade sustainability and economic feasibility without compromising on the dynamics of driving or the aesthetics of car interiors.' } },
      { section_id: 'prod-9', section_type: 'paragraph', title: null, sort_order: 38, content: { text: 'Manufacturers need to break down their production process with the goal of optimisation at each stage. Utilisation of the principles of lean manufacturing allows for streamlining of processes and procedures to eliminate waste and thereby maximise productivity. Creating large-scale carbon-neutral manufacturing processes is currently possible, difficulty comes from transition of current production and optimisation implementation, which requires proactivity and partnership with manufacturers.' } },

      // Use Stage
      { section_id: 'use-1', section_type: 'heading', title: 'Use stage', sort_order: 40, content: { level: 2 } },
      { section_id: 'use-2', section_type: 'heading', title: 'Distribution', sort_order: 41, content: { level: 3 } },
      { section_id: 'use-3', section_type: 'paragraph', title: null, sort_order: 42, content: { text: 'Distribution is another key facet of the pathway to net zero. Route optimisation can be used to ensure the shortening of journeys, consequently reducing carbon output. This can be achieved with advanced logistics software; minimising empty backhaul trips and switching fuel types or source of propulsion. The electrification of delivery fleets and limited use of air freight also aids in reducing greenhouse gas emission. Implementing just-in-time (JIT) and lean inventory practices reduces the need for extensive warehousing and transportation, enhancement that can be made at the interfaces of the life cycle stages. Further use of collaborative initiatives could facilitate companies to share transportation resources and reduce emissions.' } },
      { section_id: 'use-4', section_type: 'heading', title: 'Operation', sort_order: 43, content: { level: 3 } },
      { section_id: 'use-5', section_type: 'paragraph', title: null, sort_order: 44, content: { text: 'The transition to EV technology will already cut operational carbon emissions in contrast to fossil fuelled vehicles, shifting them up the supply chain. There is a need to drive adoption of electric and hydrogen fueled cars, due to fewer or no tailpipe emissions. The opportunity for more stringent emission standards in the iterations following Euro 6 and subsidies / incentives can drive an increase in future EV / hydrogen uptake.' } },
      { section_id: 'use-6', section_type: 'paragraph', title: null, sort_order: 45, content: { text: 'Traffic flow and emissions improvement can also be achieved via Vehicle-to-vehicle and vehicle-to-infrastructure communication. Intelligent transportation system (ITS) can be used to create intelligent intersections that reduce the waiting time and consequently the idling time and emission of the vehicles. Simulation of Urban Mobility (SUMO) software utilises real data to determine optimal control strategies.' } },
      { section_id: 'use-7', section_type: 'callout', title: 'Infrastructure Requirements', sort_order: 46, content: { type: 'info', text: 'Infrastructure must be implemented to keep up with and drive adoption of EV and hydrogen technology. Manufacturers should build an equivalent network of hydrogen refilling stations and power charging points for mass adoption of clean energy solutions. The EU Alternative Fuel Infrastructure Regulation (AFIR) outlines recommended infrastructure rollout for member states. The 2025 targets proposed in the AFIR are about 25% higher than estimated requirements to meet the projected public charging needs of the battery electric truck fleet.' } },

      // End of Life Stage
      { section_id: 'eol-1', section_type: 'heading', title: 'End of life stage', sort_order: 50, content: { level: 2 } },
      { section_id: 'eol-2', section_type: 'paragraph', title: null, sort_order: 51, content: { text: 'A large facet of the end-of-life carbon emission improvement is built into the design process. Use of remanufacturing can also be used to reduce emissions. The product\'s life span is extended by bringing a defective product to the same standard as it was when it was first manufactured. Approximately 96% of the raw materials used in manufacturing the original automotive parts are conserved through remanufacturing. Additionally, there is an approximate 40% reduction in CO2e (carbon dioxide equivalent) emissions and a 38% reduction in energy consumption during the process.' } },
      { section_id: 'eol-3', section_type: 'paragraph', title: null, sort_order: 52, content: { text: 'The circular economy can be advanced through high vehicle utilization models, such as ride hailing, car sharing, and Mobility as a Service (MaaS). These models reduce both the number of vehicles and components that are disposed of, as well as emissions resulting from inefficient private ownership. Furthermore, the establishment of re-manufacturing and recycling centres ensures that raw and critical materials in vehicles and batteries can be fully utilized. Additionally, the adoption of modular designs during vehicle development facilitates ease of disassembly and recycling.' } },

      // Challenges
      { section_id: 'chal-1', section_type: 'heading', title: 'Challenges', sort_order: 55, content: { level: 2 } },
      { section_id: 'chal-2', section_type: 'paragraph', title: null, sort_order: 56, content: { text: 'The automotive sector is strongly characterized by tailpipe emissions, which constitute those from the use of sold products. The solution to avoid the accounting of those emissions is to focus the production areas on those vehicles which do not impact the downstream scope emissions from category 11 scope 3 "use of sold products", for this reason automotive manufacturers face challenges in the choice of production or in the choice of what kind of vehicle to produce. Prioritising high-impact areas like electric taxis, delivery vehicles, and postal trucks is a time-sensitive solution with several key benefits. It accelerates market transformation and encourages innovation. Electrifying these high-use vehicles demonstrates the feasibility of electric power, exposes consumers to EVs, and aids in avoiding downstream emissions from the use of sold products.' } },
      { section_id: 'chal-3', section_type: 'heading', title: 'Consumer acceptance', sort_order: 57, content: { level: 3 } },
      { section_id: 'chal-4', section_type: 'paragraph', title: null, sort_order: 58, content: { text: 'Despite climate concerns, many consumers are still very apprehensive when it comes to purchasing a car they have to charge. One of the primary challenges that car manufacturers face in the transition is driving the adoption of new technology. This can be assisted by regulation, as well as subsidies, incentives and emission zones that benefit alternative fuel vehicle drivers, alleviating some of the associated high upfront cost.' } },
      { section_id: 'chal-5', section_type: 'heading', title: 'Infrastructure', sort_order: 59, content: { level: 3 } },
      { section_id: 'chal-6', section_type: 'paragraph', title: null, sort_order: 60, content: { text: 'Car manufacturers and national grids face challenge in the energy requirements of matching EV uptake. With constant policy change it is hard to produce predictive models that can match demand whilst also withholding capital outlay until necessary. Energy grid stability is another concern with increasing numbers of EVs. It is estimated that once 15% of cars on the road are electric, power grids will struggle. To accelerate the use of EVs, utilities must change the way they deliver power to their customers.' } },
      { section_id: 'chal-7', section_type: 'heading', title: 'Implementation challenges', sort_order: 61, content: { level: 3 } },
      { section_id: 'chal-8', section_type: 'paragraph', title: null, sort_order: 62, content: { text: 'The complexity of the automotive supply chain adds additional challenges in standardisation and transparency that must be overcome to accelerate the transition. This can further be done through stricter regulation, and collaboration between industry participants to provide the most effective solutions and beneficial outcomes.' } },

      // Best practices for decarbonisation
      { section_id: 'decarb-1', section_type: 'heading', title: 'Best practices for decarbonisation', sort_order: 65, content: { level: 2 } },
      { section_id: 'decarb-2', section_type: 'paragraph', title: null, sort_order: 66, content: { text: 'Decarbonisation of the automotive industry cannot be reliant on the single set of policies or the introduction of separate low-carbon manufacturing processes. It is the whole set of approaches that encapsules a Near-Zero solution for the sector, firm and industry. Hence a holistic approach for an automotive producer to "drive" towards sustainable mobility would require a degree of regenerative economics. A number of best practices leading to the decarbonisation of the sector can be identified.' } },
      { section_id: 'decarb-3', section_type: 'list', title: 'Key Decarbonisation Practices', sort_order: 67, content: { items: ['Vehicle electrification - Promote the development and adoption of electric vehicles (EVs) and plug-in hybrid electric vehicles (PHEVs) as they produce zero tailpipe emissions.', 'Sustainable materials - Utilise sustainable and recyclable materials in vehicle production to reduce emissions associated with manufacturing.', 'Lifecycle assessment - Producers conducting comprehensive lifecycle assessments to identify and mitigate carbon emissions at every stage.', 'Efficient manufacturing - Implement energy-efficient manufacturing processes, such as lean production, to minimise energy consumption and waste generation.', 'Supply chain decarbonisation - Encourage suppliers to reduce emissions and align with sustainable practices.', 'Circular economy - Develop a circular economy approach that emphasises recycling, reusing, and remanufacturing vehicle components and materials.', 'Renewable energy use - Power manufacturing facilities with renewable energy sources.', 'Zero-emission transport - Invest in low-emission and zero-emission transportation options for employees.', 'Light-weighting - Reduce vehicle weight through innovative engineering and material choices.', 'Alternative fuels - Develop and promote alternative fuels, such as hydrogen and biofuels.', 'Consumer education - Educate consumers about the environmental benefits of EVs and other low-emission vehicles.'] } },

      // Market and Mainstream Technology
      { section_id: 'market-1', section_type: 'heading', title: 'Market and Mainstream Technology', sort_order: 70, content: { level: 2 } },
      { section_id: 'market-2', section_type: 'heading', title: 'Industry overview', sort_order: 71, content: { level: 2 } },
      { section_id: 'market-3', section_type: 'paragraph', title: null, sort_order: 72, content: { text: 'Market value: In terms of market value, the European passengers car manufacturing industry it projected to peak at a revenue of €413,2bn by 2025 to then stabilise around €291,1bn by 2028. With a projected value increase of 16.7% from 2022 to 2028.' } },
      { section_id: 'market-4', section_type: 'paragraph', title: null, sort_order: 73, content: { text: 'Market segmentation: The market is segmented by vehicle type, where in 2023 passenger cars were the largest category at 85.2% of total volume – heavy trucks make up 2.34% of total volume, heavy buses 0.25% of total volume and light commercial vehicles making up 12.16% of the total volume. Germany is the largest producer in Europe, followed by Spain, Czechia, France, Turkey and the rest of Europe. In 2023, petrol cars were those with the highest number of registrations followed by hybrid electric vehicles, battery-electric vehicles, diesel and plug-in hybrid electric vehicles.' } },
      { section_id: 'market-5', section_type: 'paragraph', title: null, sort_order: 74, content: { text: 'Competition: There is strong rivalry due to large players with well-developed brands, however, strong growth in 2022 eased competition. Volkswagen, Daimler, PSA, and Renault are the leading multinational manufacturers in Europe. Focusing on the development of new and emerging carbon-neutral technologies are the key drivers of growth in this industry.' } },

      // Business Model
      { section_id: 'bm-1', section_type: 'heading', title: 'Business model, stakeholders and mainstream technologies', sort_order: 80, content: { level: 2 } },
      { section_id: 'bm-2', section_type: 'heading', title: 'Business model', sort_order: 81, content: { level: 3 } },
      { section_id: 'bm-3', section_type: 'paragraph', title: null, sort_order: 82, content: { text: 'The primary business model of automotive manufacturers (OEMs) is the B2B selling of hardware (vehicles) to dealerships. The vehicles are produced in large assembly lines where barebones chassis\' have third-party components attached, with customer-ready vehicles rolling off the lines. Some components are produced in house, but the vast majority of the 5000-10,000 parts per vehicle are sourced from suppliers.' } },
      { section_id: 'bm-4', section_type: 'paragraph', title: null, sort_order: 83, content: { text: 'OEMs also generate revenue via licensed garages. Licensed vendors perform maintenance and service vehicles using parts provided by the manufacturers. This forms a much smaller portion of the total revenue versus vehicle sales but generates reliable income in the short-term.' } },
      { section_id: 'bm-5', section_type: 'paragraph', title: null, sort_order: 84, content: { text: 'A more recent phenomenon is the prevalence of subscription services provided by OEMs. Examples include the Ford Pro+ fleet management software solution and BMW\'s heated seats. These are examples of innovations made by the incumbent manufacturers to retain their competitive edge in a fiercely competitive landscape of automotive giants.' } },
      { section_id: 'bm-6', section_type: 'heading', title: 'Suppliers', sort_order: 85, content: { level: 3 } },
      { section_id: 'bm-7', section_type: 'paragraph', title: null, sort_order: 86, content: { text: 'Component and part manufacturing is the primary role of suppliers. They are responsible for manufacturing and supplying various components and parts that go into the assembly of vehicles. This includes everything from transmissions to smaller components like tires, brakes, and electronic systems. Most OEMs design and manufacture their own engines.' } },
      { section_id: 'bm-8', section_type: 'callout', title: 'Supply Chain Vulnerability', sort_order: 87, content: { type: 'warning', text: 'Suppliers often operate on a JIT (Just in Time) supply model, delivering components to automakers exactly when they are needed for the production process. This minimizes inventory costs and enhances production efficiency. The risks of this approach were made excruciatingly clear during the COVID-19 pandemic when these fragile supply chains broke down due to low resilience and flexibility.' } },
      { section_id: 'bm-9', section_type: 'heading', title: 'Buyers', sort_order: 88, content: { level: 3 } },
      { section_id: 'bm-10', section_type: 'paragraph', title: null, sort_order: 89, content: { text: 'Dealerships are often the primary point of contact for individuals looking to purchase, service, and maintain vehicles. Therefore, they act as the B2C interface between OEMs and end consumers. This role positions them to have strong bargaining power, which has resulted in some manufacturers adopting the D2C approach to cut out these middlemen.' } },

      // Mainstream Technologies
      { section_id: 'tech-1', section_type: 'heading', title: 'Mainstream Technologies – ICEs, EVs, Hybrids, Autonomous Driving, Hydrogen Fuel Cells, and Batteries', sort_order: 95, content: { level: 2 } },
      { section_id: 'tech-2', section_type: 'heading', title: 'Internal combustion engines (ICEs)', sort_order: 96, content: { level: 3 } },
      { section_id: 'tech-3', section_type: 'paragraph', title: null, sort_order: 97, content: { text: 'They have been the primary powertrain technology since the inception of automotive vehicles. These have a significant impact on climate change due to their emissions of greenhouse gases, primarily carbon dioxide (CO2) and other pollutants. The transport sector accounts for 23% of global energy-related CO2 emissions and is the fastest growing contributor to climate change. Within the transport sector, road vehicles account for 70% of emissions, or 16.7% of global emissions.' } },
      { section_id: 'tech-4', section_type: 'heading', title: 'Electric vehicles (EVs)', sort_order: 98, content: { level: 3 } },
      { section_id: 'tech-5', section_type: 'paragraph', title: null, sort_order: 99, content: { text: 'They are vehicles that are powered by electricity stored in onboard batteries. Instead of relying on internal combustion engines fueled by gasoline or diesel, electric vehicles use electric motors to drive the vehicle\'s wheels. The rapid onset of this technology has resulted in 1 in 5 new cars sold in 2023 to be electric.' } },
      { section_id: 'tech-6', section_type: 'list', title: 'Types of Electric Vehicles', sort_order: 100, content: { items: ['Battery electric vehicles (BEVs) - Entirely powered by electricity stored in rechargeable high-capacity batteries. These vehicles have no internal combustion engine and produce zero tailpipe emissions.', 'Plug-in hybrid electric vehicles (PHEVs) - Combine an internal combustion engine with an electric motor and a battery. They can be charged from an external power source and can also operate using gasoline or another conventional fuel.'] } },
      { section_id: 'tech-7', section_type: 'heading', title: 'Autonomous driving', sort_order: 101, content: { level: 3 } },
      { section_id: 'tech-8', section_type: 'paragraph', title: null, sort_order: 102, content: { text: 'Autonomous driving, often referred to as self-driving or driverless technology, refers to the capability of a vehicle to operate and navigate without direct human intervention. These vehicles use a combination of sensors, cameras, radar, lidar, GPS, and advanced software to perceive their surroundings, make decisions, and control the vehicle\'s movements.' } },
      { section_id: 'tech-9', section_type: 'list', title: 'Levels of Autonomy (SAE)', sort_order: 103, content: { items: ['Level 0 (no automation) - The vehicle is entirely controlled by a human driver.', 'Level 1 (driver assistance) - Basic driver assistance systems, such as adaptive cruise control and lane-keeping assist.', 'Level 3 (conditional automation) - The vehicle can manage all aspects of driving, but the human driver needs to be available to take over.', 'Level 4 (high automation) - Vehicles can operate autonomously in specific conditions and environments.', 'Level 5 (full automation) - The highest level of autonomy, where the vehicle is fully autonomous under all conditions.'] } },

      // Industry Products
      { section_id: 'prod-types-1', section_type: 'heading', title: 'Industry products', sort_order: 110, content: { level: 2 } },
      { section_id: 'prod-types-2', section_type: 'paragraph', title: null, sort_order: 111, content: { text: 'The automotive industry has been a significant contributor to technological advancement, especially in the realm of vehicle propulsion and efficiency. The fundamental technology driving automobiles for over a century has been the Internal Combustion Engine (ICE). This technology relies on igniting a fuel-air mixture to produce high-pressure gas that moves pistons and ultimately drives the wheels.' } },
      { section_id: 'prod-types-3', section_type: 'accordion', title: 'Vehicle Technologies', sort_order: 112, content: { items: [{ title: 'Electric Vehicles (EVs)', content: 'Utilize electric motors powered by onboard batteries, represent a major technological shift. These vehicles offer zero exhaust emissions, which is crucial for urban air quality, and provide a quieter, smoother driving experience. Advances in battery technology, particularly in solid-state batteries, are expected to enhance safety features, increase energy storage capacity, and reduce charging times.' }, { title: 'Hybrid Electric Vehicles (HEVs)', content: 'Combine the ICE with electric motors to optimize fuel efficiency and reduce emissions. These vehicles can switch between the electric motor for low-speed urban driving and the ICE for higher speeds or longer distances, offering a balance between traditional and electric technologies.' }, { title: 'Plug-in Hybrid Electric Vehicles (PHEVs)', content: 'Further the concept of hybrids by featuring larger batteries that can be recharged from the grid, allowing for extended electric-only operation.' }, { title: 'Fuel Cell Vehicles (FCVs)', content: 'Produce electricity through a chemical reaction in a fuel cell—usually involving hydrogen—offering a clean alternative to battery-powered electric vehicles. The only byproducts are water and heat, making FCVs exceptionally eco-friendly. However, challenges such as the lack of hydrogen infrastructure and the high cost of fuel cell production remain significant barriers.' }] } },

      // Impacts Section
      { section_id: 'impacts-1', section_type: 'heading', title: 'Impacts', sort_order: 120, content: { level: 2 } },
      { section_id: 'impacts-2', section_type: 'heading', title: 'Introduction', sort_order: 121, content: { level: 2 } },
      { section_id: 'impacts-3', section_type: 'paragraph', title: null, sort_order: 122, content: { text: 'The automotive sector has long been seen as a symbol of progress and innovation, revolutionising how we move and interact in our increasingly interconnected world. However, this vast industry, with its intricate web of producers, suppliers, and consumers, carries significant responsibility for its profound environmental and climate change implications. It is critical that we investigate the significant environmental consequences of mass vehicle production, energy consumption, and emissions, as well as the transformative potential for sustainable technologies and policies that can help steer this industry towards a more eco-friendly and responsible future.' } },
      { section_id: 'impacts-4', section_type: 'list', title: 'Main Impacts', sort_order: 123, content: { items: ['Climate change contribution due to excessive GHG emissions', 'Decarbonisation of automotive industry in the EU and the role of EU ETS', 'Air Pollution', 'Energy Consumption', 'Resource Depletion', 'Land Use and Urban Sprawl', 'Waste Generation', 'Noise Pollution', 'Water Pollution', 'Congestion and Fuel Inefficiency', 'Biodiversity Impact', 'Public health concerns due to air pollutions', 'Lifecycle emissions', 'Ecological Disruption from Source Extraction', 'Social Impacts', 'Economical Impacts', 'Cultural and Lifestyle Impacts', 'Supply Chain Vulnerabilities'] } },

      // Climate Change Impact
      { section_id: 'climate-1', section_type: 'heading', title: 'Climate change contribution due to excessive GHG emissions', sort_order: 130, content: { level: 2 } },
      { section_id: 'climate-2', section_type: 'paragraph', title: null, sort_order: 131, content: { text: 'The automotive industry\'s contribution to climate change is primarily due to its excessive greenhouse gas (GHG) emissions. These emissions, mainly in the form of carbon dioxide (CO2), result from the burning of fossil fuels, such as gasoline and diesel, in internal combustion engine (ICE) vehicles.' } },
      { section_id: 'climate-3', section_type: 'list', title: 'Climate Change Effects', sort_order: 132, content: { items: ['Global warming - The release of CO2 and other GHGs from vehicle tailpipes traps heat in the Earth\'s atmosphere, leading to global warming.', 'Extreme weather events - Excessive GHG emissions are linked to more frequent and severe extreme weather events including hurricanes, droughts, and wildfires.', 'Rising sea levels - Increased temperatures cause polar ice caps and glaciers to melt, threatening coastal communities and low-lying islands.', 'Ocean acidification - CO2 emissions absorbed by oceans leads to ocean acidification, harming marine ecosystems and coral reefs.', 'Shifts in climate patterns - Climate change leads to altered rainfall patterns, affecting agricultural yields and human health.', 'Loss of biodiversity - Changing temperature and precipitation patterns disrupt ecosystems and impact species distribution.'] } },

      // Air Pollution
      { section_id: 'air-1', section_type: 'heading', title: 'Air Pollution', sort_order: 140, content: { level: 2 } },
      { section_id: 'air-2', section_type: 'paragraph', title: null, sort_order: 141, content: { text: 'The automotive industry significantly contributes to air pollution through its extensive production processes, as well as the operation of vehicles, which often rely on fossil fuels. This industry is one of the largest sources of urban air pollution, releasing a spectrum of harmful pollutants. The manufacturing of vehicles releases various pollutants into the air including Volatile Organic Compounds (VOCs), Carbon Monoxide (CO), Nitrogen Oxides (NOx), and Particulate Matter (PM).' } },

      // Energy Consumption
      { section_id: 'energy-1', section_type: 'heading', title: 'Energy Consumption', sort_order: 145, content: { level: 2 } },
      { section_id: 'energy-2', section_type: 'paragraph', title: null, sort_order: 146, content: { text: 'The automotive industry is one of the largest consumers of energy globally. Manufacturing facilities for automobiles are substantial energy users, primarily due to activities like metal stamping, welding, painting, and assembly. The typical energy sources are electricity and natural gas, with a significant portion of this energy coming from non-renewable sources.' } },

      // Resource Depletion
      { section_id: 'resource-1', section_type: 'heading', title: 'Resource Depletion', sort_order: 150, content: { level: 2 } },
      { section_id: 'resource-2', section_type: 'paragraph', title: null, sort_order: 151, content: { text: 'The automotive industry is a significant consumer of natural resources, contributing to global resource depletion. This includes the extraction of metals, petroleum-based products, and rare earth elements, which are all essential for vehicle production. Steel, aluminum, copper, and other metals are fundamental to vehicle construction. Mining these resources is energy-intensive and leads to significant environmental degradation including habitat destruction, water pollution, and soil erosion.' } },

      // Regulation and Legislation
      { section_id: 'reg-1', section_type: 'heading', title: 'Regulation and Legislation', sort_order: 160, content: { level: 2 } },
      { section_id: 'reg-2', section_type: 'heading', title: 'Carbon neutrality', sort_order: 161, content: { level: 2 } },
      { section_id: 'reg-3', section_type: 'paragraph', title: null, sort_order: 162, content: { text: 'In line with Paris Agreement commitments the EU aims to be climate-neutral by 2050. The European Commission set out its climate neutral vision in November 2018 as part of the "Clean Planet for all: A European strategic long-term vision for a prosperous, modern, competitive and climate neutral economy" document. The European Climate Law proposed in March 2020 enshrined the 2050 goal into law, at the same time the EU submitted its long-term strategy to the UNFCCC as part of their Nationally Determined Contribution (NDCs), used to enforce better transparency between participants. Member States are required to develop national long-term strategies to meet the commitments.' } },
      { section_id: 'reg-4', section_type: 'callout', title: 'Fit for 55 Package', sort_order: 163, content: { type: 'info', text: 'As an intermediary step the Green Deal includes the Fit for 55 Package. It tightens the EU\'s existing CO2 emission performance standards from the current goal of a 37.5% reduction by 2030. European Union leaders want a 55% cut in net greenhouse gas emissions by 2030, a ban on new internal combustion cars and vans by 2035 and new legislation requiring batteries to be more sustainable.' } },

      // EU ETS
      { section_id: 'ets-1', section_type: 'heading', title: 'EU Emissions Trading System', sort_order: 165, content: { level: 3 } },
      { section_id: 'ets-2', section_type: 'list', title: 'EU ETS Key Features', sort_order: 166, content: { items: ['Incentivising emission reductions - Provides economic incentives for automotive companies to reduce their emissions. Companies that can reduce their emissions efficiently have the opportunity to profit by selling their excess allowances.', 'Setting emissions limit - Sets specific emissions limits for the automotive industry, compelling companies to reduce their emissions over time.', 'Integration with broader policies - Works in tandem with other initiatives such as emissions standards for vehicles and support for electric vehicle infrastructure.', 'Transparency and reporting - Requires companies to accurately report their emissions, enabling regulators to monitor progress.', 'Compliance and penalties - Companies that exceed their emissions allowances are subject to financial penalties.', 'Encouraging investment in clean technologies - Motivates automotive manufacturers to invest in research and development of low-emission and zero-emission technologies.'] } },

      // Cars and vans sale ban
      { section_id: 'ban-1', section_type: 'heading', title: 'Cars and vans sale ban', sort_order: 170, content: { level: 2 } },
      { section_id: 'ban-2', section_type: 'paragraph', title: null, sort_order: 171, content: { text: 'In March 2023, the EU Council enacted a regulation that set forth more stringent performance standards for CO2 emissions in new cars and vans. The new regulation is designed to decrease emissions from road transportation, which now accounts for the largest portion of emissions from the transportation sector.' } },
      { section_id: 'ban-3', section_type: 'list', title: 'Key Targets', sort_order: 172, content: { items: ['New vehicles will have a 55% decrease in CO2 emissions, while vans will have a 50% decrease, between 2030 and 2034, compared to 2021 levels.', 'Starting in 2035, there will be a complete elimination of carbon dioxide (CO2) emissions from both new cars and vans, implying a sale ban of ICE cars and vans.', 'Emission credits granted to manufacturers for eco-innovations will be limited to a maximum of 4g/km per year starting from 2030 (down from 7g/km).'] } },

      // Vehicle Emission Standards
      { section_id: 'euro-1', section_type: 'heading', title: 'Vehicle Emission Standards', sort_order: 175, content: { level: 2 } },
      { section_id: 'euro-2', section_type: 'paragraph', title: null, sort_order: 176, content: { text: 'Formally introduced in 1992, the Euro Emissions Standards define acceptable exhaust standards effecting land surface vehicles sold in the European Union, European Economic Area, and the UK. Euro 6, the most recent iteration was released in 2015. The rules cover nitrogen oxide (NOx), carbon monoxide (CO), hydrocarbons (THC and NMHC), and particulate matter (PM).' } },
      { section_id: 'euro-3', section_type: 'paragraph', title: null, sort_order: 177, content: { text: 'Euro 6 introduced a new test on public roads to simulate Real Driving Emissions (RDE) after the diesel emission scandal of 2014, which used software to lower emissions in the laboratory when a test was being conducted.' } },
      { section_id: 'euro-4', section_type: 'callout', title: 'Euro 7 Regulation', sort_order: 178, content: { type: 'info', text: 'The Euro 7 regulation sets forth guidelines for the discharge of exhaust emissions from road vehicles, as well as additional forms of emissions including tyre abrasion and brake particle emissions. Additionally, it establishes criteria for the longevity of batteries. The law maintains the current Euro 6 exhaust emission limitations for vehicles and vans, while implementing more stringent requirements for solid particles.' } },

      // Clean Mobility
      { section_id: 'clean-1', section_type: 'heading', title: 'Clean Mobility', sort_order: 180, content: { level: 2 } },
      { section_id: 'clean-2', section_type: 'paragraph', title: null, sort_order: 181, content: { text: 'The Vehicle Emissions Standards aim to curb current emissions and promote development of lower carbon emitting vehicles, at the same time the EU Clean mobility package supports the development and adoption of electric vehicles (EV), encouraging the use of alternative fuels. It involves 82 initiatives that lays the foundation for how the EU transport system can achieve its green and digital transformation and become more resilient to future crises. The result will be a 90% cut in emissions by 2050, delivered by a smart, competitive, safe, accessible and affordable transport system.' } },
      { section_id: 'clean-3', section_type: 'list', title: 'Clean Mobility Targets', sort_order: 182, content: { items: ['30 million zero-emission cars in operation on European roads by 2030', 'Nearly all cars, vans, buses and heavy-duty vehicles will be zero-emission by 2050', '3 million public charging points by 2030', 'Doubling high-speed rail traffic', 'Developing extra cycling infrastructure over the next 10 years'] } },

      // Circular Economy
      { section_id: 'ce-1', section_type: 'heading', title: 'Circular Economy', sort_order: 185, content: { level: 2 } },
      { section_id: 'ce-2', section_type: 'paragraph', title: null, sort_order: 186, content: { text: 'The European Commission adopted the new Circular Economy Action Plan (CEAP) in March 2020. With the goal to reduce pressure on natural resources and create sustainable growth and jobs, it affects products throughout their lifecycle, from design to disposal. 35 Actions are implemented in the action plan, detailing a sustainable product policy framework, key product policy value chains, a need for less waste, circularity, and cost cutting actions.' } },
      { section_id: 'ce-3', section_type: 'list', title: 'Monitoring Framework', sort_order: 187, content: { items: ['Production and Consumption', 'Waste Management', 'Secondary Raw Materials', 'Competitiveness and Innovation', 'Global Sustainability and Resilience'] } },
      { section_id: 'ce-4', section_type: 'paragraph', title: null, sort_order: 188, content: { text: 'For the automotive industry the action plan is intertwined throughout the product lifecycle. Design of new products must consider sustainable material choice, considering the embedded carbon of each component. End-of-Life Vehicle (ELV) Regulations mean vehicles must be designed for recycling and easy disassembly. Extended Producer Responsibility (EPR) schemes mean manufacturers are held accountable for the entire product life cycle, including collection and recycling of vehicle components when they reach the end of their useful life.' } },

      // Supply Chain Transparency
      { section_id: 'sct-1', section_type: 'heading', title: 'Supply Chain Transparency', sort_order: 190, content: { level: 2 } },
      { section_id: 'sct-2', section_type: 'paragraph', title: null, sort_order: 191, content: { text: 'The Green Deal calls for greater supply chain transparency, with the goal to better track carbon emissions caused before components are sourced, as well as reducing the use of critical elements and affecting the high-risk areas they are sourced from.' } },
      { section_id: 'sct-3', section_type: 'accordion', title: 'Key Supply Chain Regulations', sort_order: 192, content: { items: [{ title: 'EU Conflicts Minerals Regulation', content: 'Aims to prevent or reduce the sourcing of minerals from regions where profits fund armed conflict. Covering tin, tantalum, tungsten and gold (3TGs) sourced from the Democratic Republic of the Congo and adjoining countries, and minerals from other high-risk areas.' }, { title: 'Battery Regulation (EU) 2023/1542', content: 'Has objectives to synchronise European product standards for all categories of batteries, establish an efficient internal European market for secondary raw materials for batteries, and mitigate adverse environmental impacts throughout the manufacturing, utilisation, and disposal stages of all batteries.' }, { title: 'Critical Raw Materials (CRM) Act', content: 'Integral in helping to promote sustainability, resource efficiency, and the development of a circular economy in the EU.' }, { title: 'Carbon Border Adjustment Mechanism (CBAM)', content: 'A border tax that increases the cost of importing high-carbon products into the EU, providing local low-carbon players a competitive advantage.' }] } },

      // EV Infrastructure
      { section_id: 'evi-1', section_type: 'heading', title: 'EV Infrastructure', sort_order: 195, content: { level: 2 } },
      { section_id: 'evi-2', section_type: 'paragraph', title: null, sort_order: 196, content: { text: 'Regulation 2023/1804 on the deployment of alternative fuels infrastructure lays down mandatory minimum targets for the deployment of publicly accessible recharging and refuelling infrastructures for road vehicles. The Regulation provides for minimum recharging stations and pools that member states should arrange for. Under the Regulation, a "recharging station" is a physical installation for the recharging of electric vehicles.' } },
      { section_id: 'evi-3', section_type: 'paragraph', title: null, sort_order: 197, content: { text: 'The Regulation deals with recharging stations for electric, ammonia, biomass fuels, including biogas, and biofuels, synthetic and paraffinic fuels, and pools and with the deployment of sufficient hydrogen refuelling infrastructure that is essential in order to make large-scale use of hydrogen-powered vehicles.' } },

      // Drivers of Change
      { section_id: 'doc-1', section_type: 'heading', title: 'Drivers of change', sort_order: 200, content: { level: 2 } },
      { section_id: 'doc-2', section_type: 'heading', title: 'Introduction', sort_order: 201, content: { level: 2 } },
      { section_id: 'doc-3', section_type: 'paragraph', title: null, sort_order: 202, content: { text: 'The automotive industry is currently navigating through an era of significant change, driven by a multitude of factors that are reshaping vehicle design, manufacturing processes, and market dynamics. These drivers of change encompass technological advancements, regulatory developments, environmental considerations, and shifts in consumer preferences, all of which are propelling the industry towards more sustainable and innovative practices.' } },
      { section_id: 'doc-4', section_type: 'accordion', title: 'Key Drivers of Change', sort_order: 203, content: { items: [{ title: 'Economic Shifts', content: 'The automotive industry is highly sensitive to global economic conditions, which significantly influence consumer purchasing behavior, production volumes, and strategic planning. Economic fluctuations impact various facets of the automotive sector, from raw material prices and production costs to consumer demand and investment in new technologies.' }, { title: 'Workforce Welfare and Employment Standards', content: 'The automotive industry\'s focus on crew welfare and labor standards is increasingly recognized as a critical driver of change. High labour standards are essential for protecting workers\' rights and ensuring their safety and well-being.' }, { title: 'Investor Relations and Shareholder Activism', content: 'Investor and shareholder activism is increasingly becoming a significant driver of change in the automotive industry, pushing companies towards more sustainable and socially responsible business practices. ESG criteria are now integral to many investors\' decision-making processes.' }, { title: 'Stricter Waste Management and Recycling Policies', content: 'The automotive industry is significantly impacted by stricter waste management and recycling policies, which are becoming increasingly important in light of global sustainability efforts.' }, { title: 'Insurance and Liability Considerations', content: 'Insurance and liability considerations are increasingly influential in the automotive industry, particularly as vehicles become more technologically advanced and the industry faces shifts towards electrification and autonomous driving.' }, { title: 'Security and Cybersecurity measures', content: 'As vehicles become increasingly connected and reliant on sophisticated software systems, security and cybersecurity measures have emerged as critical drivers of change in the automotive industry.' }, { title: 'Impact of Climate Change on Product Development', content: 'The impact of climate change is profoundly influencing product development in the automotive industry. Vehicles are increasingly being designed to withstand extreme weather conditions.' }] } },

      // Existing and Forthcoming Technologies
      { section_id: 'eft-1', section_type: 'heading', title: 'Existing and forthcoming decarbonisation technologies and opportunities', sort_order: 210, content: { level: 2 } },
      { section_id: 'eft-2', section_type: 'heading', title: 'Introduction', sort_order: 211, content: { level: 2 } },
      { section_id: 'eft-3', section_type: 'paragraph', title: null, sort_order: 212, content: { text: 'The automotive industry is at the forefront of technological innovation, with a range of decarbonisation technologies and opportunities emerging to address the environmental challenges associated with vehicle production and use. This section outlines both existing and forthcoming technologies that are pivotal in driving the industry towards a more sustainable future.' } },
      { section_id: 'eft-4', section_type: 'heading', title: 'Forthcoming technologies', sort_order: 213, content: { level: 2 } },
      { section_id: 'eft-5', section_type: 'accordion', title: 'Decarbonisation Technologies', sort_order: 214, content: { items: [{ title: 'Battery Technology Advancements', content: 'Solid-state batteries are expected to enhance safety features, increase energy storage capacity, and reduce charging times. Research is also focusing on developing more sustainable battery chemistries with reduced reliance on rare earth elements.' }, { title: 'Hydrogen Fuel Cells', content: 'Hydrogen fuel cell technology offers a clean alternative to battery-powered electric vehicles. The only byproducts are water and heat, making FCVs exceptionally eco-friendly. Research is ongoing to reduce the cost of fuel cell production and develop hydrogen infrastructure.' }, { title: 'Lightweight Materials', content: 'Advanced materials such as carbon fiber reinforced polymers, aluminum alloys, and high-strength steel are being developed to reduce vehicle weight, improving fuel efficiency and extending the range of electric vehicles.' }, { title: 'Vehicle-to-Grid (V2G) Technology', content: 'V2G technology allows electric vehicles to store excess energy from the grid and feed it back when needed, helping to balance grid demand and integrate renewable energy sources more effectively.' }, { title: 'Autonomous Vehicles', content: 'Autonomous driving technology has the potential to optimize driving patterns, reduce accidents, and improve traffic flow, leading to lower emissions and energy consumption.' }] } },

      // Transition Plan Credibility
      { section_id: 'tpc-1', section_type: 'heading', title: 'Transition plan credibility', sort_order: 220, content: { level: 2 } },
      { section_id: 'tpc-2', section_type: 'heading', title: 'Introduction', sort_order: 221, content: { level: 2 } },
      { section_id: 'tpc-3', section_type: 'paragraph', title: null, sort_order: 222, content: { text: 'The credibility of transition plans is a crucial factor in assessing the sustainability efforts of automotive companies. Financial institutions and investors are increasingly scrutinizing the transition plans of automakers to ensure they are aligned with global climate goals and are capable of delivering on their commitments. A credible transition plan should demonstrate a clear pathway to decarbonisation, supported by measurable targets, realistic timelines, and adequate financial resources.' } },
      { section_id: 'tpc-4', section_type: 'heading', title: 'Transition plan credibility - TPT', sort_order: 223, content: { level: 2 } },
      { section_id: 'tpc-5', section_type: 'paragraph', title: null, sort_order: 224, content: { text: 'The Transition Plan Taskforce (TPT) provides guidance on how companies should develop and disclose their transition plans. The framework emphasizes the importance of setting science-based targets, engaging with stakeholders, and ensuring transparency in reporting progress towards climate goals.' } },
      { section_id: 'tpc-6', section_type: 'heading', title: 'Effectiveness of transition plans', sort_order: 225, content: { level: 2 } },
      { section_id: 'tpc-7', section_type: 'paragraph', title: null, sort_order: 226, content: { text: 'The effectiveness of a transition plan is determined by its ability to achieve the stated goals within the specified timeframe. Key indicators of effectiveness include the rate of emissions reduction, the adoption of low-carbon technologies, and the alignment of investment strategies with climate objectives. Regular monitoring and reporting are essential to track progress and make necessary adjustments to the plan.' } },
      { section_id: 'tpc-8', section_type: 'heading', title: 'Carbon lock-in risk', sort_order: 227, content: { level: 2 } },
      { section_id: 'tpc-9', section_type: 'paragraph', title: null, sort_order: 228, content: { text: 'Carbon lock-in risk refers to the possibility that investments in long-lived, carbon-intensive assets may become stranded as the world transitions to a low-carbon economy. In the automotive sector, this risk is particularly relevant for companies that continue to invest heavily in internal combustion engine technology. A credible transition plan should address carbon lock-in risk by outlining strategies to phase out high-carbon assets and invest in low-carbon alternatives.' } },
      { section_id: 'tpc-10', section_type: 'heading', title: 'Which GHG emission metrics are relevant for the sector?', sort_order: 229, content: { level: 2 } },
      { section_id: 'tpc-11', section_type: 'list', title: 'Relevant GHG Metrics', sort_order: 230, content: { items: ['Scope 1 emissions - Direct emissions from company-owned sources (manufacturing facilities, company vehicles)', 'Scope 2 emissions - Indirect emissions from purchased electricity and heat', 'Scope 3 Category 1 - Purchased goods and services (upstream supply chain)', 'Scope 3 Category 11 - Use of sold products (most significant for automotive, covering vehicle lifetime emissions)', 'Well-to-Wheel (WTW) emissions - Comprehensive measure including fuel production and vehicle operation'] } },

      // Automotive Target Setting (SBTi)
      { section_id: 'sbti-1', section_type: 'heading', title: 'Automotive target setting following SBTi sectoral approach', sort_order: 235, content: { level: 2 } },
      { section_id: 'sbti-2', section_type: 'paragraph', title: null, sort_order: 236, content: { text: 'SBTi has recently published a new methodology for the target setting of the land transport sector. The methodology clarifies some of the previously undefined target setting methodologies for an automotive manufacturer to accurately assess its carbon budget.' } },
      { section_id: 'sbti-3', section_type: 'list', title: 'General Criteria', sort_order: 237, content: { items: ['All targets, whether absolute or intensity, which cover land transport activities must be on a Well-to-Wheel (WTW) basis.', 'The automotive manufacturer must set sector SDA targets and disclose and report base year, most recent year and target year activity data with two metrics.', 'The emissions covered when using the SDA Transport Tool must be in scope 3, related to transportation activities outside the company\'s organisational boundary.', 'Automakers are prohibited from utilising the transport SDA to establish targets for scope 3 category 11, only for the other categories of scope 3.', 'Where intensity targets set for scope 3 using the transport SDA are aggregated with other scope 3 targets on an absolute basis, the intensity sub-target shall also be disclosed.'] } },
      { section_id: 'sbti-4', section_type: 'heading', title: 'Specific criteria for automaker target setting', sort_order: 238, content: { level: 2 } },
      { section_id: 'sbti-5', section_type: 'paragraph', title: null, sort_order: 239, content: { text: 'When setting a target boundary the automotive manufacturer should use the SBTi "Corporate Near-Term Criteria" and "Corporate Net-Zero Standard Criteria". Those apply for scope 1, 2 and 3 emissions, but not for the category 11 of scope 3. Specifically, the portfolio of emissions across vehicle category should be specified, without geographical exclusions. The calculation of emissions should be adjusted to reflect real life emissions using the WLTP (Worldwide Harmonised Light Vehicle Test Procedure) or the WHDC (World Harmonised Heavy-Duty Certification).' } },
      { section_id: 'sbti-6', section_type: 'callout', title: 'ICE Phase-Out Requirement', sort_order: 240, content: { type: 'warning', text: 'For the calculation and the target setting of the category 11 scope 3 emissions the automakers shall use a WTW basis and must set absolute emission reduction targets consistent with limiting global warming to 1.5°C. Moreover, there should be the phase out of ICE cars and vans by 2035 in Europe and by 2040 globally. Statement required: "Company X commits to work toward the phase out of new internal combustion engine vehicles by 2035 in leading markets and by 2040 globally."' } },
      { section_id: 'sbti-7', section_type: 'heading', title: 'Emission intensity vs absolute targets', sort_order: 241, content: { level: 2 } },
      { section_id: 'sbti-8', section_type: 'paragraph', title: null, sort_order: 242, content: { text: 'SBTi allows for automaker targets to be expressed in intensity terms, but if doing so the companies must disclose credible and justifiable projected target year unit sales and use them to calculate intensity reductions equivalent to the absolute target ambition. For the disclosure of scope 3 category 11 automaker targets, they should be in passenger-kilometers or metric tonne-kilometer of sold manufactured vehicles.' } },
      { section_id: 'sbti-9', section_type: 'heading', title: 'Minimum ambition', sort_order: 243, content: { level: 2 } },
      { section_id: 'sbti-10', section_type: 'paragraph', title: null, sort_order: 244, content: { text: 'The minimum ambition for automotive companies should be aligned with limiting global warming to 1.5°C above pre-industrial levels. This requires significant reductions in emissions across all scopes, with particular emphasis on scope 3 category 11 emissions from the use of sold products.' } },

      // KPIs for the Automotive Sector
      { section_id: 'kpi-1', section_type: 'heading', title: 'KPIs for the automotive sector', sort_order: 250, content: { level: 2 } },
      { section_id: 'kpi-2', section_type: 'heading', title: 'Introduction', sort_order: 251, content: { level: 2 } },
      { section_id: 'kpi-3', section_type: 'paragraph', title: null, sort_order: 252, content: { text: 'Key Performance Indicators (KPIs) are essential for measuring the progress of automotive companies towards their sustainability goals. These indicators provide a standardized way to assess the environmental performance of companies and compare their progress against industry benchmarks and climate scenarios.' } },
      { section_id: 'kpi-4', section_type: 'heading', title: 'Methodology', sort_order: 253, content: { level: 2 } },
      { section_id: 'kpi-5', section_type: 'paragraph', title: null, sort_order: 254, content: { text: 'The methodology for assessing automotive KPIs is based on the ACT Initiative framework, which provides a comprehensive approach to evaluating the credibility of transition plans. The methodology considers both quantitative metrics (such as emissions intensity and R&D spending) and qualitative factors (such as governance and stakeholder engagement).' } },
      { section_id: 'kpi-6', section_type: 'heading', title: 'Automotive physical emission intensity', sort_order: 255, content: { level: 2 } },
      { section_id: 'kpi-7', section_type: 'paragraph', title: null, sort_order: 256, content: { text: 'Physical emission intensity is a key metric for assessing the carbon performance of automotive companies. It measures the amount of CO2 emissions per unit of output (typically gCO2/km for passenger vehicles). This metric is particularly useful for comparing the performance of different vehicle models and tracking progress towards emissions reduction targets.' } },
      { section_id: 'kpi-8', section_type: 'heading', title: 'Alignment of scope 1 and 2 emission reduction targets', sort_order: 257, content: { level: 2 } },
      { section_id: 'kpi-9', section_type: 'paragraph', title: null, sort_order: 258, content: { text: 'This KPI assesses whether the automotive manufacturer\'s scope 1 and 2 emission reduction targets are aligned with the pathway required to limit global warming to 1.5°C. The assessment considers the ambition of the targets, the timeframe for achievement, and the credibility of the underlying assumptions.' } },
      { section_id: 'kpi-10', section_type: 'heading', title: 'Trend in past scope 3 upstream emission intensity', sort_order: 259, content: { level: 2 } },
      { section_id: 'kpi-11', section_type: 'paragraph', title: null, sort_order: 260, content: { text: 'This indicator tracks the historical trend in scope 3 upstream emissions, which include emissions from the supply chain (purchased goods and services, transportation of materials, etc.). A declining trend indicates that the company is successfully reducing emissions throughout its supply chain.' } },
      { section_id: 'kpi-12', section_type: 'heading', title: 'Cumulative scope 3 downstream emissions', sort_order: 261, content: { level: 2 } },
      { section_id: 'kpi-13', section_type: 'paragraph', title: null, sort_order: 262, content: { text: 'This KPI measures the total emissions from the use of sold products over their lifetime. For automotive companies, this is the most significant emissions category and includes all tailpipe emissions from vehicles during their operational life. The cumulative nature of this metric highlights the long-term impact of current production decisions.' } },
      { section_id: 'kpi-14', section_type: 'heading', title: 'R&D spending on low-carbon technologies', sort_order: 263, content: { level: 2 } },
      { section_id: 'kpi-15', section_type: 'paragraph', title: null, sort_order: 264, content: { text: 'This indicator measures the proportion of R&D spending dedicated to low-carbon technologies such as electric vehicles, fuel cells, and battery technology. A higher proportion of R&D spending on low-carbon technologies indicates a stronger commitment to the transition to a sustainable business model.' } },
      { section_id: 'kpi-16', section_type: 'heading', title: 'Share of low-carbon vehicles', sort_order: 265, content: { level: 2 } },
      { section_id: 'kpi-17', section_type: 'paragraph', title: null, sort_order: 266, content: { text: 'Share of low-carbon vehicles is a KPI which deepens the assessment of borrowers transition plan credibility related to the areas of revenue and production, decarbonisation levers and GHG targets. It is a measure of the company\'s sales in the last five years and expected growth in the next three years of low-carbon vehicles, as compared with the expectations required in the sector under a 1.5°C scenario.' } },
      { section_id: 'kpi-18', section_type: 'table', title: 'Low-Carbon Vehicle Benchmarks', sort_order: 267, content: { headers: ['Benchmark/Target', 'Year(s)'], rows: [['35-40% of new vehicle sales as low-carbon vehicles', '2026'], ['50% of new vehicle sales as low-carbon vehicles', '2030'], ['100% zero-emission vehicles (ZEV) (all sales)', '2035'], ['+5-7% annual growth in low-carbon vehicle sales', '2024-2027'], ['BEV market share projected to reach 50-60% (ACEA)', '2030'], ['Full decarbonization (net-zero emissions) - European Climate Law', '2050']] } },

      // Locked-in Emissions
      { section_id: 'locked-1', section_type: 'heading', title: 'Locked-in emissions', sort_order: 275, content: { level: 2 } },
      { section_id: 'locked-2', section_type: 'paragraph', title: null, sort_order: 276, content: { text: 'Definition of Locked-in emissions associated with key assets from reporting years until 2030 and 2050 in tonnes of carbon dioxide equivalent: under the ATP-col guidance framework locked-in emissions can be defined as "the sum of the estimated scope 1 and 2 GHG emissions over the operating lifetime of the active and firmly planned assets. The key assets are those owned or controlled by the company, and they consist of existing and planned assets (such as stationary or mobile installations, facilities and equipment) that are source of either significant direct or energy-indirect GHG emissions. Firmly planned key assets are those that the company will most likely deploy within the next 5 years."' } },
      { section_id: 'locked-3', section_type: 'paragraph', title: null, sort_order: 277, content: { text: 'Definition of cumulative locked-in GHG emissions associated with the direct use-phase GHG emissions of sold products: under the ATP-col guidance framework locked-in emissions from sold products can be defined as follows, "the volume of sales of products in the reporting year multiplied by the sum of estimated direct use-phase GHG emissions over their expected lifetime".' } },
      { section_id: 'locked-4', section_type: 'heading', title: 'Formulas for locked-in emissions', sort_order: 278, content: { level: 2 } },
      { section_id: 'locked-5', section_type: 'list', title: 'Locked-in Emissions Formulas', sort_order: 279, content: { items: ['Formula locked-in emissions for key assets - Based on remaining operational lifetime of active and planned facilities', 'Formula for fossil fuel assets - Emissions calculated based on asset operational parameters', 'Formula for locked-in emission associated with sold products - Emissions calculated over the products lifetime, incorporating sales volume and emissions intensity', 'Formula for cumulative Locked-in emissions - Breaks down locked-in emissions based on key sources: facilities (scope 1 and 2) and products (scope 3)'] } },
      { section_id: 'locked-6', section_type: 'heading', title: 'How should financial institutions assess the carbon-lock in risk of automotive manufacturers?', sort_order: 280, content: { level: 2 } },
      { section_id: 'locked-7', section_type: 'paragraph', title: null, sort_order: 281, content: { text: 'Financial institutions encounter a dynamic risk when evaluating locked-in emissions, which is inherently linked to the borrower\'s carbon budget. Cumulative locked-in emissions influence the attribution factor as specified by UNEP-Fi and PCAF. A borrower\'s locked-in emissions indicate a commitment gap when the cumulative locked-in emissions exceed the permitted or anticipated carbon budget outlined in the targets. Consequently, financial institutions should address locked-in emissions that exceed the permitted carbon budget to minimise their financed emissions.' } },
      { section_id: 'locked-8', section_type: 'heading', title: 'How to understand whether a borrower\'s carbon budget is credible?', sort_order: 282, content: { level: 2 } },
      { section_id: 'locked-9', section_type: 'paragraph', title: null, sort_order: 283, content: { text: 'There are allocation methodologies which have been accepted as more or less credible. In order to assess whether the borrowers are aligned with the carbon budget of the sector, financial institutions need to understand what the allocation methodology are and if they are science-based and internationally accepted. ACT for its methodology identified that there are only 2 allocation methodologies which can be used in order to scientifically allocate future emissions which have been developed by SBTi.' } },
      { section_id: 'locked-10', section_type: 'accordion', title: 'Allocation Methodologies', sort_order: 284, content: { items: [{ title: 'Sectoral Decarbonisation Approach (SDA)', content: 'The first method that applies a convergence approach to translate a sectoral pathway derived from a 2°C scenario to set company-specific targets that account for growth and initial performance. It relies on physical production and convergence sharing principles when applied to "homogenous" sectors. The methodology assumes that the carbon intensity reduction of a company converges with the reduction of the sector at a similar rate.' }, { title: 'Absolute Contraction Approach (ACA)', content: 'The ACA method is applicable where there is the presence of a heterogeneous sector, where the determination of a meaningful emission intensity is less straightforward. This method is used for companies to set emission reduction targets that are aligned with the global annual emissions reduction rate required to meet 1.5°C or WB-2°C. The methodology is applicable whatever the initial performance of the company is, however the drawback is that it does not acknowledge the past efforts and investments which the borrower have made to engage their low-carbon transition.' }] } },

      // Automotive Components
      { section_id: 'comp-1', section_type: 'heading', title: 'Automotive components to assess scope 3 upstream emissions', sort_order: 290, content: { level: 2 } },
      { section_id: 'comp-2', section_type: 'paragraph', title: null, sort_order: 291, content: { text: 'This section is applicable when borrowers lack GHG emissions data for category 1 scope 3 related to acquired goods and services. This is the information that the component supplier must provide to the manufacturer for vehicle production. The justification for utilising these components is that car manufacturers are unlikely to obtain comprehensive emissions data or emissions data per unit of product, whether expressed in intensity or absolute terms, from their suppliers, owing to the absence of carbon accounting as a standardised practice in the hard-to-abate sector.' } },

      // Aluminum
      { section_id: 'alu-1', section_type: 'heading', title: 'Aluminum', sort_order: 295, content: { level: 2 } },
      { section_id: 'alu-2', section_type: 'paragraph', title: null, sort_order: 296, content: { text: 'Aluminum plays an essential role in the automotive sector due to its lightweight properties, which significantly contribute to improving vehicle efficiency, reducing fuel consumption, and enhancing the performance of electric vehicles (EVs). It is estimated that around 40% of the end use of aluminum in Europe is due to the transport sector. Its low density, approximately 2.71 g/cm3 (one-third that of steel), makes it highly suitable for producing lightweight vehicles that consume less energy. For example, reducing a vehicle\'s weight by 10% can lead to a 6-8% improvement in fuel efficiency.' } },
      { section_id: 'alu-3', section_type: 'paragraph', title: null, sort_order: 297, content: { text: 'The production of aluminum, however, is highly energy-intensive, particularly the process of refining bauxite ore into alumina and then smelting it into aluminum metal. This process, primarily through the Hall-Héroult method, requires large amounts of electricity, and the emissions associated with aluminium production vary significantly depending on the energy source used.' } },
      { section_id: 'alu-4', section_type: 'heading', title: 'Share of secondary aluminum used', sort_order: 298, content: { level: 3 } },
      { section_id: 'alu-5', section_type: 'paragraph', title: null, sort_order: 299, content: { text: 'The Share of Secondary Aluminum Used (SASU) is a crucial KPI as it tracks the percentage of recycled aluminum in production, directly reducing carbon emissions and production costs. Using secondary aluminum requires less energy than primary aluminum, contributing to a lower environmental footprint and promoting resource conservation.' } },
      { section_id: 'alu-6', section_type: 'list', title: 'Secondary Aluminum Targets', sort_order: 300, content: { items: ['42% by 2030', '44% by 2035', '56% by 2050'] } },
      { section_id: 'alu-7', section_type: 'heading', title: 'Share of near zero emission primary aluminum production', sort_order: 301, content: { level: 3 } },
      { section_id: 'alu-8', section_type: 'paragraph', title: null, sort_order: 302, content: { text: 'This KPI tracks the proportion of primary aluminum produced using near-zero or zero-emission processes. Near-zero emission aluminum production typically involves the use of renewable electricity for smelting and the implementation of carbon capture technologies. This is a critical metric for assessing the decarbonisation progress of the aluminum supply chain.' } },
      { section_id: 'alu-9', section_type: 'list', title: 'Near-Zero Emission Aluminum Targets', sort_order: 303, content: { items: ['16% by 2030', '49% by 2035', '100% by 2050'] } },
      { section_id: 'alu-10', section_type: 'heading', title: 'GHG emissions per tonne of aluminum', sort_order: 304, content: { level: 3 } },
      { section_id: 'alu-11', section_type: 'table', title: 'Aluminum Emission Intensity Benchmarks', sort_order: 305, content: { headers: ['Region/Process', 'tCO2/t Aluminum'], rows: [['Primary Al (global average)', '16.5'], ['Primary Al (EU average)', '6.8'], ['Primary Al (China average)', '18.5'], ['Secondary Al (recycled)', '0.5-2.0'], ['Near-zero emission primary Al', '<2.0']] } },

      // Steel
      { section_id: 'steel-1', section_type: 'heading', title: 'Steel', sort_order: 310, content: { level: 2 } },
      { section_id: 'steel-2', section_type: 'paragraph', title: null, sort_order: 311, content: { text: 'Steel is one of the most widely used materials in automotive manufacturing, accounting for a significant portion of a vehicle\'s total weight. The production of steel is energy-intensive and a major source of industrial CO2 emissions. Understanding the carbon intensity of steel used in vehicles is crucial for assessing the overall environmental impact of automotive production.' } },
      { section_id: 'steel-3', section_type: 'heading', title: 'Carbon intensity of steel used', sort_order: 312, content: { level: 3 } },
      { section_id: 'steel-4', section_type: 'paragraph', title: null, sort_order: 313, content: { text: 'This KPI measures the average carbon intensity of steel used in vehicle production, expressed as tonnes of CO2 per tonne of steel. The benchmark varies depending on the production route used (blast furnace vs. electric arc furnace) and the proportion of recycled content.' } },
      { section_id: 'steel-5', section_type: 'table', title: 'Steel Carbon Intensity Benchmarks', sort_order: 314, content: { headers: ['Production Route', 'tCO2/t Steel'], rows: [['Blast Furnace-Basic Oxygen Furnace (BF-BOF)', '1.8-2.2'], ['Electric Arc Furnace (EAF) - grid mix', '0.4-0.8'], ['EAF - renewable electricity', '<0.2'], ['Green steel (hydrogen-based DRI)', '<0.1']] } },
      { section_id: 'steel-6', section_type: 'heading', title: 'Recycled content in steel used', sort_order: 315, content: { level: 3 } },
      { section_id: 'steel-7', section_type: 'paragraph', title: null, sort_order: 316, content: { text: 'This indicator measures the proportion of recycled steel (scrap steel) used in vehicle production. Higher recycled content generally correlates with lower carbon intensity, as the EAF route using scrap steel is significantly less carbon-intensive than primary steel production via the BF-BOF route.' } },
      { section_id: 'steel-8', section_type: 'heading', title: 'Share of green steel used', sort_order: 317, content: { level: 3 } },
      { section_id: 'steel-9', section_type: 'paragraph', title: null, sort_order: 318, content: { text: 'Green steel refers to steel produced using hydrogen-based direct reduced iron (DRI) processes or other near-zero emission technologies. This KPI tracks the adoption of green steel by automotive manufacturers as they seek to decarbonise their supply chains.' } },

      // Plastics
      { section_id: 'plas-1', section_type: 'heading', title: 'Plastics', sort_order: 325, content: { level: 2 } },
      { section_id: 'plas-2', section_type: 'paragraph', title: null, sort_order: 326, content: { text: 'Plastics are used extensively in modern vehicles for interior components, exterior panels, and various functional parts. The automotive industry is increasingly focused on reducing the environmental impact of plastics through the use of recycled content, bio-based materials, and improved recyclability.' } },
      { section_id: 'plas-3', section_type: 'heading', title: 'Percentage of recycled plastic used', sort_order: 327, content: { level: 3 } },
      { section_id: 'plas-4', section_type: 'paragraph', title: null, sort_order: 328, content: { text: 'This KPI measures the proportion of recycled plastic content in the plastics used for vehicle production. Increasing the use of recycled plastics helps to reduce the demand for virgin plastics derived from fossil fuels and supports the development of a circular economy in the automotive sector.' } },
      { section_id: 'plas-5', section_type: 'heading', title: 'Plastics Recycling & PRP-ELV Directive', sort_order: 329, content: { level: 3 } },
      { section_id: 'plas-6', section_type: 'paragraph', title: null, sort_order: 330, content: { text: 'The proposed revision of the End-of-Life Vehicles (ELV) Directive includes targets for the recycled plastic content in new vehicles. This reflects the EU\'s commitment to promoting circularity in the automotive sector and reducing the environmental impact of plastic waste.' } },
      { section_id: 'plas-7', section_type: 'heading', title: 'Percentage of biomass-derived plastics', sort_order: 331, content: { level: 3 } },
      { section_id: 'plas-8', section_type: 'paragraph', title: null, sort_order: 332, content: { text: 'This KPI tracks the proportion of biomass-derived plastics used in production, ensuring that these plastics have lower life cycle GHG emissions than equivalent plastics made from fossil fuels. The use of biomass-derived plastics plays a key role in transitioning from fossil-based to renewable materials. The target is to increase the use of biomass-derived plastics to 18% of the total plastics used by 2050. Interim targets could be set at 10% by 2030.' } },
      { section_id: 'plas-9', section_type: 'heading', title: 'Percentage of chemically recycled plastics', sort_order: 333, content: { level: 3 } },
      { section_id: 'plas-10', section_type: 'paragraph', title: null, sort_order: 334, content: { text: 'This KPI measures the percentage of plastics used in operations that are sourced from chemically recycled processes. Chemical recycling offers an innovative solution for processing plastics that cannot be mechanically recycled due to quality degradation. The goal is to have 19% of all plastics used by the automaker come from chemically recycled sources by 2050, with interim benchmarks at 5-10% by 2030.' } },

      // Glass
      { section_id: 'glass-1', section_type: 'heading', title: 'Glass', sort_order: 340, content: { level: 2 } },
      { section_id: 'glass-2', section_type: 'heading', title: 'Carbon footprint', sort_order: 341, content: { level: 3 } },
      { section_id: 'glass-3', section_type: 'paragraph', title: null, sort_order: 342, content: { text: 'The carbon footprint of automotive glass is a crucial metric for assessing the environmental impact of materials used in vehicle manufacturing, especially for fleet operations. By assessing the carbon footprint per square meter of glass (e.g., 7 kg CO₂/m² for Low-E glass), the financial institution can gauge whether the automaker is committed to using sustainable materials that minimize environmental impact.' } },
      { section_id: 'glass-4', section_type: 'callout', title: 'Glass Carbon Footprint Benchmark', sort_order: 343, content: { type: 'info', text: 'The carbon footprint per square meter (CFunit) of Low-E glass in the automotive sector is 7 kg CO₂/m². This benchmark is used by automotive glass manufacturers, such as AGC and Guardian Glass, to ensure their products are aligned with sustainability goals for reducing greenhouse gas emissions in fleet vehicles.' } },
      { section_id: 'glass-5', section_type: 'heading', title: 'GHG emission intensity', sort_order: 344, content: { level: 3 } },
      { section_id: 'glass-6', section_type: 'paragraph', title: null, sort_order: 345, content: { text: 'The current approach to understanding emissions in the glass sector involves reusing the pathways provided by the International Energy Agency\'s (IEA) SDS. However, a challenge arises from the fact that these pathways are not fully tailored to the glass industry.' } },
      { section_id: 'glass-7', section_type: 'list', title: 'Glass Scope 1 & 2 Emission Intensity Projections', sort_order: 346, content: { items: ['By 2030: 73% of 2020 baseline', 'By 2035: 62% of 2020 baseline', 'By 2040: 53% of 2020 baseline', 'By 2045: 44% of 2020 baseline', 'By 2050: 35% of 2020 baseline'] } },

      // Consolidated Q&A
      { section_id: 'qa-1', section_type: 'heading', title: 'Consolidated Q&A', sort_order: 350, content: { level: 2 } },
      { section_id: 'qa-2', section_type: 'paragraph', title: null, sort_order: 351, content: { text: 'This consolidated Q&A includes sector specific qualitative questions in order to understand risks and impacts associated to the transition plan of the financial institution\'s clients. The Q&A framework provides a structured approach to assessing the credibility of automotive companies\' transition plans and their alignment with climate objectives.' } },
    ];

    // Define all sources
    const sources = [
      { source_number: 1, title: 'Assessing Low-Carbon Transition: Automobile', author: 'CDP Worldwide & ADEME', year: '2021', url: 'https://actinitiative.org/act-methodologies/' },
      { source_number: 2, title: 'Cars and Vans', author: 'International Energy Agency (IEA)', year: '2022', url: 'https://www.iea.org/reports/cars-and-vans' },
      { source_number: 3, title: 'Net Zero by 2050', author: 'IEA', year: '2021', url: 'https://www.iea.org/reports/net-zero-by-2050' },
      { source_number: 4, title: 'Vision 2050: A strategy to decarbonise the global transport sector by mid-century', author: 'International Council on Clean Transportation', year: '2020', url: 'https://theicct.org/sites/default/files/publications/ICCT_Vision2050_sept2020.pdf' },
      { source_number: 5, title: 'New Mobility: Today\'s technology and policy landscape', author: 'ICCT', year: '2017', url: 'https://theicct.org/publication/new-mobility-todays-technology-and-policy-landscape/' },
      { source_number: 6, title: 'Industry-based Guidance on Implementing IFRS S2', author: 'IFRS', year: '2022', url: 'https://www.ifrs.org/projects/completed-projects/2023/climate-related-disclosures/appendix-b-industry-based-disclosure-requirements/' },
      { source_number: 7, title: 'Transport Science-based Target Setting Guidance', author: 'Science Based Targets initiative', year: '2021', url: 'https://sciencebasedtargets.org/resources/files/SBT-transport-guidance-Final.pdf' },
      { source_number: 8, title: 'Carbon performance assessment of automobile manufacturers: Note on methodology', author: 'Transition Pathways Initiative', year: '2020', url: 'https://www.transitionpathwayinitiative.org/publications/28.pdf' },
      { source_number: 9, title: 'ACT Automobile Methodology', author: 'ACT Initiative', year: '2020', url: 'https://actinitiative.org/wp-content/uploads/pdf/act-auto-vf-2020-11-13.pdf' },
      { source_number: 10, title: 'Regulation (EU) 2023/1542 - Battery Regulation', author: 'European Parliament and Council', year: '2023', url: null },
      { source_number: 11, title: 'Automotive Manufacturing and Net Zero', author: 'ICM Summit', year: '2023', url: 'https://icm-summit.com/automatization-robotization/automotive-manufacturing-and-net-zero/' },
      { source_number: 12, title: 'Why net-zero supply chains are the next big opportunity for business', author: 'EY UK', year: '2022', url: 'https://www.ey.com/en_uk/supply-chain/why-net-zero-supply-chains-are-the-next-big-opportunity-for-business' },
      { source_number: 13, title: 'Environmental sustainability in automotive supply chains', author: 'Automotive World', year: '2022', url: 'https://www.automotiveworld.com/articles/environmental-sustainability-in-automotive-supply-chains/' },
      { source_number: 14, title: 'Carbon management is crucial for the automotive industry', author: 'Automotive World', year: '2022', url: 'https://www.automotiveworld.com/articles/carbon-management-is-crucial-for-the-automotive-industry/' },
      { source_number: 15, title: 'The Circular Cars Initiative', author: 'World Economic Forum', year: '2021', url: 'https://www.weforum.org/projects/the-circular-cars-initiative' },
      { source_number: 16, title: 'Barriers to Using ESG Data for Investment Decisions', author: 'MDPI Sustainability', year: '2022', url: 'https://www.mdpi.com/2071-1050/14/9/5157' },
      { source_number: 17, title: 'Eco-Material Selection for Lightweight Vehicle Design', author: 'IntechOpen', year: '2019', url: 'https://www.intechopen.com/chapters/68988' },
      { source_number: 18, title: 'Extended Producer Responsibility for Automotive', author: 'EPR Certificate Online', year: '2023', url: 'https://eprcertificate.online/extended-producer-responsibility-for-automotive/' },
      { source_number: 19, title: 'Comment: We need a more secure supply chain if we are to achieve net zero', author: 'The Engineer', year: '2022', url: 'https://www.theengineer.co.uk/content/opinion/comment-we-need-a-more-secure-supply-chain-if-we-are-to-achieve-net-zero/' },
      { source_number: 20, title: 'First rise in 11 months for UK car production', author: 'SMMT', year: '2022', url: 'https://www.smmt.co.uk/2022/06/first-rise-in-11-months-for-uk-car-production/' },
      { source_number: 21, title: 'Carbon-neutral manufacturing is possible: here\'s how', author: 'World Economic Forum', year: '2022', url: 'https://www.weforum.org/agenda/2022/01/carbon-neutral-manufacturing-possible-net-zero/' },
      { source_number: 22, title: 'The future of automobiles depends on carbon control', author: 'World Economic Forum', year: '2021', url: 'https://www.weforum.org/agenda/2021/05/the-future-of-automobiles-clean-energy-decarbonization/' },
      { source_number: 23, title: 'What is Lean Manufacturing and the 5 Principles Used?', author: 'TWI Global', year: '2022', url: 'https://www.twi-global.com/technical-knowledge/faqs/faq-what-is-lean-manufacturing' },
      { source_number: 24, title: 'Traffic flow and emissions improvement via Vehicle-to-vehicle and vehicle-to-infrastructure communication', author: 'Asian Journal of Control', year: '2021', url: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/asjc.2508' },
      { source_number: 25, title: 'A review of the AFIR proposal: Public infrastructure needs to support zero-emission truck fleet transition', author: 'ICCT', year: '2022', url: 'https://theicct.org/publication/afir-eu-hdv-infrastructure-mar22/' },
      { source_number: 26, title: 'Remanufacturing', author: 'Car Parts Industries EU', year: '2022', url: 'https://carpartsindustries.eu/what-we-do/remanufacturing' },
      { source_number: 27, title: 'How the circular economy could change how cars are made', author: 'World Economic Forum', year: '2020', url: 'https://www.weforum.org/agenda/2020/12/how-the-circular-economy-could-forever-change-how-cars-are-made/' },
      { source_number: 28, title: 'Three ways to speed up the transition to electric vehicles', author: 'World Economic Forum', year: '2019', url: 'https://www.weforum.org/agenda/2019/03/three-ways-to-speed-up-the-transition-to-electric-vehicles/' },
      { source_number: 29, title: 'European Climate Law (Regulation EU 2021/1119)', author: 'European Parliament', year: '2021', url: null },
      { source_number: 30, title: 'Fit for 55 Package', author: 'European Commission', year: '2021', url: null },
      { source_number: 31, title: 'CO2 emission performance standards for cars and vans', author: 'EU Council', year: '2023', url: null },
      { source_number: 32, title: 'Euro 6 and Euro 7 Emission Standards', author: 'European Commission', year: '2015/2024', url: null },
      { source_number: 33, title: 'EU Clean Mobility Package', author: 'European Commission', year: '2021', url: null },
      { source_number: 34, title: 'Circular Economy Action Plan (CEAP)', author: 'European Commission', year: '2020', url: null },
      { source_number: 35, title: 'EU Conflicts Minerals Regulation (EU) 2017/821', author: 'European Parliament', year: '2017', url: null },
      { source_number: 36, title: 'Alternative Fuels Infrastructure Regulation (AFIR) 2023/1804', author: 'European Parliament', year: '2023', url: null },
      { source_number: 37, title: 'Critical Raw Materials (CRM) Act', author: 'European Commission', year: '2023', url: null },
      { source_number: 38, title: 'Carbon Border Adjustment Mechanism (CBAM)', author: 'European Commission', year: '2023', url: null },
      { source_number: 39, title: 'SBTi Land Transport Target Setting Methodology', author: 'Science Based Targets initiative', year: '2024', url: 'https://sciencebasedtargets.org/' },
      { source_number: 40, title: 'PCAF Global GHG Accounting and Reporting Standard', author: 'Partnership for Carbon Accounting Financials', year: '2022', url: null },
      { source_number: 41, title: 'UNEP-FI Guidelines for Climate Target Setting', author: 'UNEP Finance Initiative', year: '2022', url: null },
      { source_number: 42, title: 'Transition Plan Taskforce (TPT) Disclosure Framework', author: 'TPT', year: '2023', url: 'https://transitiontaskforce.net/' },
      { source_number: 43, title: 'ATP-Col Guidance Framework for Locked-in Emissions', author: 'ATP', year: '2023', url: null },
      { source_number: 44, title: 'IEA Sustainable Development Scenario (SDS)', author: 'IEA', year: '2020', url: null },
      { source_number: 45, title: 'Plastics Europe Roadmap for Net Zero', author: 'Plastics Europe', year: '2022', url: null },
      { source_number: 46, title: 'ACEA - European Automobile Manufacturers\' Association Market Data', author: 'ACEA', year: '2023', url: null },
      { source_number: 47, title: 'European Environment Agency - CO2 Fleet Targets', author: 'EEA', year: '2023', url: null },
      { source_number: 48, title: 'ISO 14067:2018 - Carbon footprint of products', author: 'ISO', year: '2018', url: null },
      { source_number: 49, title: 'ISO 14064-1:2018 - GHG quantification and reporting', author: 'ISO', year: '2018', url: null },
      { source_number: 50, title: 'Directive (EU) 2018/2001 - Renewable Energy Directive', author: 'European Parliament', year: '2018', url: null },
      { source_number: 51, title: 'IPCC AR6 Climate Change Report', author: 'IPCC', year: '2022', url: null },
      { source_number: 52, title: 'Global EV Outlook 2023', author: 'IEA', year: '2023', url: 'https://www.iea.org/reports/global-ev-outlook-2023' },
    ];

    // Insert sections
    const sectionsToInsert = sections.map(s => ({
      page_id: pageId,
      section_id: s.section_id,
      section_type: s.section_type,
      title: s.title,
      sort_order: s.sort_order,
      content: s.content
    }));

    const { error: sectionsError } = await supabase
      .from('page_sections')
      .insert(sectionsToInsert);

    if (sectionsError) {
      console.error('Error inserting sections:', sectionsError);
      throw sectionsError;
    }
    console.info(`Inserted ${sectionsToInsert.length} sections`);

    // Insert sources
    const sourcesToInsert = sources.map(s => ({
      page_id: pageId,
      source_number: s.source_number,
      title: s.title,
      author: s.author,
      year: s.year,
      url: s.url
    }));

    const { error: sourcesError } = await supabase
      .from('page_sources')
      .insert(sourcesToInsert);

    if (sourcesError) {
      console.error('Error inserting sources:', sourcesError);
      throw sourcesError;
    }
    console.info(`Inserted ${sourcesToInsert.length} sources`);

    // Update page timestamp
    await supabase
      .from('pages')
      .update({ 
        updated_at: new Date().toISOString(),
        last_updated: new Date().toISOString().split('T')[0]
      })
      .eq('id', pageId);

    return new Response(
      JSON.stringify({ 
        success: true, 
        message: `Successfully seeded Automotive sector content: ${sectionsToInsert.length} sections, ${sourcesToInsert.length} sources` 
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error: unknown) {
    console.error('Error seeding Automotive content:', error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    return new Response(
      JSON.stringify({ error: errorMessage }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
